jobs:
- name: bootstrap
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: terraform-example

  - task: create-update
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: terraform-example }
    params:
      STACK_NAME: example
      S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_DEFAULT_REGION: {{aws_default_region}}

- name: teardown
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: terraform-example
  - task: destroy
    file: pipeline-tasks/terraform-destroy.yml
    input_mapping: { terraform-templates: terraform-example }
    params:
      STACK_NAME: example
      S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_DEFAULT_REGION: {{aws_default_region}}

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: https://github.com/LinuxBozo/cg-pipeline-tasks.git
    branch: terraform

- name: terraform-example
  type: git
  source:
    uri: https://github.com/LinuxBozo/terraform-example.git
    branch: master
